---
###############################################
# Playbook Ansible pour déployer CloudBeaver
# Compatible Debian 12/13
# Auteur: Tiago
# Date: 2025-10-16
###############################################

- name: Déploiement de CloudBeaver
  hosts: cloudbeaver_servers
  become: yes
  vars:
    cloudbeaver_version: "24.3.4"
    cloudbeaver_dir: "/opt/cloudbeaver"
    cloudbeaver_user: "cloudbeaver"
    cloudbeaver_port: 8978
    postgres_driver_version: "42.7.4"

  tasks:
    - name: Vérification que le système est Debian
      assert:
        that:
          - ansible_distribution == "Debian"
        fail_msg: "Ce playbook est conçu uniquement pour Debian"

    - name: Mise à jour du cache APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installation des paquets requis
      apt:
        name:
          - openjdk-17-jre-headless
          - wget
          - unzip
          - curl
          - python3-passlib
        state: present

    - name: Vérification de l'installation de Java
      command: java -version
      register: java_version
      changed_when: false

    - name: Affichage de la version Java
      debug:
        msg: "Java installé: {{ java_version.stderr_lines[0] }}"

    - name: Création de l'utilisateur système CloudBeaver
      user:
        name: "{{ cloudbeaver_user }}"
        system: yes
        shell: /bin/false
        home: "{{ cloudbeaver_dir }}"
        create_home: no

    - name: Vérification si CloudBeaver est déjà installé
      stat:
        path: "{{ cloudbeaver_dir }}/run-server.sh"
      register: cloudbeaver_installed

    - name: Sauvegarde de l'installation existante
      command: "mv {{ cloudbeaver_dir }} {{ cloudbeaver_dir }}.backup.{{ ansible_date_time.epoch }}"
      when: cloudbeaver_installed.stat.exists

    - name: Téléchargement de CloudBeaver
      get_url:
        url: "https://github.com/dbeaver/cloudbeaver/releases/download/{{ cloudbeaver_version }}/cloudbeaver-{{ cloudbeaver_version }}.zip"
        dest: "/tmp/cloudbeaver.zip"
        mode: '0644'

    - name: Extraction de CloudBeaver
      unarchive:
        src: "/tmp/cloudbeaver.zip"
        dest: "/tmp/"
        remote_src: yes

    - name: Déplacement vers le répertoire d'installation
      command: "mv /tmp/cloudbeaver {{ cloudbeaver_dir }}"
      args:
        creates: "{{ cloudbeaver_dir }}"

    - name: Configuration des permissions
      file:
        path: "{{ cloudbeaver_dir }}"
        owner: "{{ cloudbeaver_user }}"
        group: "{{ cloudbeaver_user }}"
        recurse: yes

    - name: Rendre le script de démarrage exécutable
      file:
        path: "{{ cloudbeaver_dir }}/run-server.sh"
        mode: '0755'

    - name: Création du répertoire des drivers JDBC
      file:
        path: "{{ cloudbeaver_dir }}/drivers/{{ item }}"
        state: directory
        owner: "{{ cloudbeaver_user }}"
        group: "{{ cloudbeaver_user }}"
        mode: '0755'
      loop:
        - postgresql
        - oracle

    - name: Téléchargement du driver PostgreSQL
      get_url:
        url: "https://jdbc.postgresql.org/download/postgresql-{{ postgres_driver_version }}.jar"
        dest: "{{ cloudbeaver_dir }}/drivers/postgresql/postgresql-{{ postgres_driver_version }}.jar"
        owner: "{{ cloudbeaver_user }}"
        group: "{{ cloudbeaver_user }}"
        mode: '0644'
      ignore_errors: yes

    - name: Génération du mot de passe admin
      set_fact:
        admin_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"

    - name: Création du service systemd
      template:
        dest: /etc/systemd/system/cloudbeaver.service
        content: |
          [Unit]
          Description=CloudBeaver Server
          After=network.target

          [Service]
          Type=simple
          User={{ cloudbeaver_user }}
          Group={{ cloudbeaver_user }}
          WorkingDirectory={{ cloudbeaver_dir }}
          ExecStart={{ cloudbeaver_dir }}/run-server.sh
          Restart=on-failure
          RestartSec=10
          StandardOutput=journal
          StandardError=journal

          [Install]
          WantedBy=multi-user.target
      notify: Reload systemd

    - name: Activation du service CloudBeaver
      systemd:
        name: cloudbeaver
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Attente du démarrage de CloudBeaver
      wait_for:
        port: "{{ cloudbeaver_port }}"
        delay: 5
        timeout: 60

    - name: Sauvegarde des informations de connexion
      template:
        dest: /root/cloudbeaver-info.txt
        mode: '0600'
        content: |
          ========================================
          Informations d'installation CloudBeaver
          ========================================
          Date d'installation: {{ ansible_date_time.iso8601 }}
          Version CloudBeaver: {{ cloudbeaver_version }}
          Serveur: {{ ansible_hostname }} ({{ ansible_default_ipv4.address }})

          Installation:
          - Répertoire: {{ cloudbeaver_dir }}
          - Utilisateur système: {{ cloudbeaver_user }}
          - Port: {{ cloudbeaver_port }}

          Accès Web:
          - URL: http://{{ ansible_default_ipv4.address }}:{{ cloudbeaver_port }}
          - Premier utilisateur admin à créer lors de la première connexion
          - Mot de passe suggéré: {{ admin_password }}

          Drivers JDBC installés:
          - PostgreSQL: Version {{ postgres_driver_version }}
          - Oracle: À installer manuellement (voir documentation)

          Commandes utiles:
          - Statut: systemctl status cloudbeaver
          - Arrêt: systemctl stop cloudbeaver
          - Démarrage: systemctl start cloudbeaver
          - Redémarrage: systemctl restart cloudbeaver
          - Logs: journalctl -u cloudbeaver -f

          Configuration:
          - Fichier de configuration: {{ cloudbeaver_dir }}/conf/
          - Données: {{ cloudbeaver_dir }}/workspace/

          Prochaines étapes:
          1. Accédez à l'interface web: http://{{ ansible_default_ipv4.address }}:{{ cloudbeaver_port }}
          2. Créez le premier compte administrateur
          3. Pour Oracle, téléchargez le driver JDBC depuis:
             https://www.oracle.com/database/technologies/appdev/jdbc-downloads.html
             Et placez-le dans: {{ cloudbeaver_dir }}/drivers/oracle/
             Puis redémarrez: systemctl restart cloudbeaver

          ========================================

    - name: Nettoyage des fichiers temporaires
      file:
        path: /tmp/cloudbeaver.zip
        state: absent

    - name: Affichage des informations de connexion
      debug:
        msg:
          - "=========================================="
          - "Installation de CloudBeaver terminée!"
          - "=========================================="
          - "URL d'accès: http://{{ ansible_default_ipv4.address }}:{{ cloudbeaver_port }}"
          - "Mot de passe suggéré: {{ admin_password }}"
          - "Informations sauvegardées dans: /root/cloudbeaver-info.txt"
          - "IMPORTANT: Créez le compte administrateur lors de la première connexion"
          - "Pour Oracle DB, installez manuellement ojdbc11.jar"
          - "=========================================="

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes
