---
###############################################
# Playbook Ansible pour déployer CloudBeaver via Docker
# Compatible Debian 12/13
# Auteur: Tiago
# Date: 2025-10-16
###############################################

- name: Déploiement de CloudBeaver via Docker
  hosts: cloudbeaver_servers
  become: yes

  tasks:
    - name: Vérification que le système est Debian
      assert:
        that:
          - ansible_distribution == "Debian"
        fail_msg: "Ce playbook est conçu uniquement pour Debian"

    - name: Téléchargement du script d'installation
      get_url:
        url: https://raw.githubusercontent.com/tiagomatiastm-prog/cloudbeaver-installer/master/install-cloudbeaver.sh
        dest: /tmp/install-cloudbeaver.sh
        mode: '0755'

    - name: Exécution du script d'installation
      command: /tmp/install-cloudbeaver.sh
      register: installation_output

    - name: Affichage du résultat de l'installation
      debug:
        var: installation_output.stdout_lines

    - name: Récupération des informations de connexion
      slurp:
        path: /root/cloudbeaver-info.txt
      register: cloudbeaver_info

    - name: Affichage des informations de connexion
      debug:
        msg: "{{ cloudbeaver_info.content | b64decode }}"

    - name: Nettoyage du script temporaire
      file:
        path: /tmp/install-cloudbeaver.sh
        state: absent
