---
###############################################
# Playbook Ansible pour déployer CloudBeaver via Docker
# Compatible Debian 12/13
# Auteur: Tiago
# Date: 2025-10-16
###############################################

- name: Déploiement de CloudBeaver via Docker
  hosts: cloudbeaver_servers
  become: yes

  tasks:
    - name: Vérification que le système est Debian
      assert:
        that:
          - ansible_distribution == "Debian"
        fail_msg: "Ce playbook est conçu uniquement pour Debian"

    - name: Installation de CloudBeaver via curl
      shell: curl -fsSL https://raw.githubusercontent.com/tiagomatiastm-prog/cloudbeaver-installer/master/install-cloudbeaver.sh | bash
      register: installation_output

    - name: Affichage du résultat de l'installation
      debug:
        var: installation_output.stdout_lines
